export default [
  {
    id: 1,
    chosen: false,
    category: 'language',
    title: 'Some test lang wo id',
    fullTitle: 'Example',
    link: '#',
    icon: 'img/flags/gb.svg',
  },
  {
    id: 1,
    chosen: true,
    category: 'language',
    title: 'Some test lang wo id',
    fullTitle: 'Example',
    link: '#',
    icon: 'img/flags/gb.svg',
  },
  {
    id: 1,
    chosen: true,
    category: 'language',
    title: 'Some test lang wo id',
    fullTitle: 'Example',
    link: '#',
    icon: 'img/flags/gb.svg',
  },
  {
    id: 1,
    chosen: false,
    category: 'language',
    title: 'Some test lang wo id',
    fullTitle: 'Example',
    link: '#',
    icon: 'img/flags/gb.svg',
  },

  {
    id: 1,
    chosen: false,
    category: 'language',
    title: 'Some test lang wo id',
    fullTitle: 'Example',
    link: '#',
    icon: 'img/flags/gb.svg',
  },
  {
    id: 1,
    chosen: false,
    category: 'language',
    title: 'Some test lang wo id',
    fullTitle: 'Example',
    link: '#',
    icon: 'img/flags/gb.svg',
  },
  {
    id: 1,
    chosen: false,
    category: 'school-topic',
    title: 'Some test lang wo id',
    fullTitle: 'Example',
    link: '#',
    icon: 'img/flags/gb.svg',
  },
  {
    id: 1,
    chosen: false,
    category: 'language',
    title: 'Some test lang wo id',
    fullTitle: 'Example',
    link: '#',
    icon: 'img/flags/gb.svg',
  },

  {
    id: 1,
    chosen: false,
    category: 'language',
    title: 'Some test lang wo id',
    fullTitle: 'Example',
    link: '#',
    icon: 'img/flags/gb.svg',
  },
  {
    id: 1,
    chosen: false,
    category: 'quiz',
    title: 'Some test lang wo id',
    fullTitle: 'Example',
    link: '#',
    icon: 'img/flags/gb.svg',
  },
];
