export default [
  {
    id: 10,
    chosen: false,
    category: 'school-topic',
    title: 'Biochemistry',
    fullTitle: 'Biochemistry',
    link: '#',
  },
  {
    id: 11,
    chosen: true,
    category: 'school-topic',
    title: 'Czech',
    fullTitle: 'Czech',
    link: '#',
  },
  {
    id: 12,
    chosen: false,
    category: 'school-topic',
    title: 'History',
    fullTitle: 'History',
    link: '#',
  },
  {
    id: 13,
    chosen: true,
    category: 'school-topic',
    title: 'Math',
    fullTitle: 'Math',
    link: '#',
  },
  {
    id: 14,
    chosen: true,
    category: 'school-topic',
    title: 'Biology',
    fullTitle: 'Biology',
    link: '#',
  },
  {
    id: 15,
    chosen: false,
    category: 'school-topic',
    title: 'Psycholgy',
    fullTitle: 'Psycholgy',
    link: '#',
  },

  {
    id: 16,
    chosen: false,
    category: 'quiz',
    title: 'A good quiz',
    fullTitle: 'Example',
    link: '#',
  },
  {
    id: 17,
    chosen: false,
    category: 'quiz',
    title: 'American history',
    fullTitle: 'Example',
    link: '#',
  },
  {
    id: 18,
    chosen: false,
    category: 'quiz',
    title: 'Spanish history',
    fullTitle: 'Example',
    link: '#',
  },
  {
    id: 19,
    chosen: false,
    category: 'quiz',
    title: 'TV Shows',
    fullTitle: 'Example',
    link: '#',
  },
  {
    id: 20,
    chosen: false,
    category: 'quiz',
    title: 'Czech presidents',
    fullTitle: 'Example',
    link: '#',
  },
  {
    id: 21,
    chosen: false,
    category: 'quiz',
    title: 'Difficult quiz',
    fullTitle: 'Example',
    link: '#',
  },
]
