export default [
  {
    id: 1,
    chosen: true,
    category: 'language',
    title: 'English',
    fullTitle: 'English',
    link: '#',
    icon: 'img/flags/gb.svg',
  },
  {
    id: 1,
    chosen: true,
    category: 'language',
    title: 'German',
    fullTitle: 'German',
    link: '#',
    icon: 'img/flags/de.svg',
  },
  {
    id: 1,
    chosen: true,
    category: 'language',
    title: 'Danish',
    fullTitle: 'Danish',
    link: '#',
    icon: 'img/flags/dk.svg',
  },
  {
    id: 1,
    chosen: true,
    category: 'language',
    title: 'French',
    fullTitle: 'French',
    link: '#',
    icon: 'img/flags/fr.svg',
  },
  {
    id: 1,
    chosen: true,
    category: 'language',
    title: 'Swedish',
    fullTitle: 'Swedish',
    link: '#',
    icon: 'img/flags/se.svg',
  },
  {
    id: 1,
    chosen: true,
    category: 'language',
    title: 'Norwegian',
    fullTitle: 'Norwegian',
    link: '#',
    icon: 'img/flags/no.svg',
  },
  {
    id: 1,
    chosen: true,
    category: 'language',
    title: 'Dutch',
    fullTitle: 'Dutch',
    link: '#',
    icon: 'img/flags/nl.svg',
  },
  {
    id: 1,
    chosen: true,
    category: 'language',
    title: 'Japanese',
    fullTitle: 'Japanese',
    link: '#',
    icon: 'img/flags/jp.svg',
  },
  {
    id: 1,
    chosen: true,
    category: 'language',
    title: 'Mandarin',
    fullTitle: 'Mandarin',
    link: '#',
    icon: 'img/flags/cn.svg',
  },
  {
    id: 1,
    chosen: true,
    category: 'language',
    title: 'Spanish',
    fullTitle: 'Spanish',
    link: '#',
    icon: 'img/flags/es.svg',
  },

  {
    id: 1,
    chosen: false,
    category: 'school-topic',
    title: 'Biochemistry',
    fullTitle: 'Biochemistry',
    link: '#',
  },
  {
    id: 1,
    chosen: true,
    category: 'school-topic',
    title: 'Czech',
    fullTitle: 'Czech',
    link: '#',
  },
  {
    id: 1,
    chosen: false,
    category: 'school-topic',
    title: 'History',
    fullTitle: 'History',
    link: '#',
  },
  {
    id: 1,
    chosen: true,
    category: 'school-topic',
    title: 'Math',
    fullTitle: 'Math',
    link: '#',
  },
  {
    id: 1,
    chosen: true,
    category: 'school-topic',
    title: 'Biology',
    fullTitle: 'Biology',
    link: '#',
  },
  {
    id: 1,
    chosen: false,
    category: 'school-topic',
    title: 'Psycholgy',
    fullTitle: 'Psycholgy',
    link: '#',
  },

  {
    id: 1,
    chosen: false,
    category: 'quiz',
    title: 'A good quiz',
    fullTitle: 'Example',
    link: '#',
  },
  {
    id: 1,
    chosen: false,
    category: 'quiz',
    title: 'American history',
    fullTitle: 'Example',
    link: '#',
  },
  {
    id: 1,
    chosen: false,
    category: 'quiz',
    title: 'Spanish history',
    fullTitle: 'Example',
    link: '#',
  },
  {
    id: 1,
    chosen: false,
    category: 'quiz',
    title: 'TV Shows',
    fullTitle: 'Example',
    link: '#',
  },
  {
    id: 1,
    chosen: false,
    category: 'quiz',
    title: 'Czech presidents',
    fullTitle: 'Example',
    link: '#',
  },
  {
    id: 1,
    chosen: false,
    category: 'quiz',
    title: 'Difficult quiz',
    fullTitle: 'Example',
    link: '#',
  },
];
