export default [
  {
    id: 1,
    name: 'Shasdasdasdasle',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo placeat facere eveniet, necessitatibus modi quasi nulla. Explicabo odit ea ullam eaque commodi excepturi eum accusamus, temporibus fugit nostrum voluptates eveniet?',
    img: 'https://placeimg.com/550/300/people',
    priceNew: '10',
    priceOld: '20',
    percent: '15',
    currency: 'CZK',
    creditCost: '1050',
    extra: {
      city: 'Brno',
      country: 'CZ',
      validFrom: '01.01.19',
      validUntil: '01.01.20',
      provider: 'HEUREKA',
      email: 'info@yasdadsd.cz',
      phone: '123 392 133',
      address: 'Divalid 3, 232 Wrappi',
    },
  },

  {
    id: 2,
    name: 'Short title 2',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo placeat facere eveniet, necessitatibus modi quasi nulla. Explicabo odit ea ullam eaque commodi excepturi eum accusamus, temporibus fugit nostrum voluptates eveniet?',
    img: 'https://placeimg.com/550/300/nature',
    priceNew: '120',
    priceOld: '2033',
    percent: '32',
    currency: 'CZK',
    creditCost: '600',
    extra: {
      city: 'Brno',
      country: 'CZ',
      validFrom: '01.01.19',
      validUntil: '01.01.20',
      provider: 'HEUREKA',
      email: 'info@yasdadsd.cz',
      phone: '123 392 133',
      address: 'Divalid 3, 232 Wrappi',
    },
  },

  {
    id: 3,
    name: 'test 123 12321312',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo placeat facere eveniet, necessitatibus modi quasi nulla. Explicabo odit ea ullam eaque commodi excepturi eum accusamus, temporibus fugit nostrum voluptates eveniet?',
    img: 'https://placeimg.com/550/300/grayscale',
    priceNew: '1084',
    priceOld: '230',
    percent: '63',
    currency: 'ASD',
    creditCost: '420',
    extra: {
      city: 'Brno',
      country: 'CZ',
      validFrom: '01.01.19',
      validUntil: '01.01.20',
      provider: 'HEUREKA',
      email: 'info@yasdadsd.cz',
      phone: '123 392 133',
      address: 'Divalid 3, 232 Wrappi',
    },
  },

  {
    id: 4,
    name: 'Short title',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo placeat facere eveniet, necessitatibus modi quasi nulla. Explicabo odit ea ullam eaque commodi excepturi eum accusamus, temporibus fugit nostrum voluptates eveniet?',
    img: 'https://placeimg.com/550/301/people',
    priceNew: '10',
    priceOld: '20',
    percent: '31',
    currency: 'CZK',
    creditCost: '100',
    extra: {
      city: 'Brno',
      country: 'CZ',
      validFrom: '01.01.19',
      validUntil: '01.01.20',
      provider: 'HEUREKA',
      email: 'info@yasdadsd.cz',
      phone: '123 392 133',
      address: 'Divalid 3, 232 Wrappi',
    },
  },
];
